#!/bin/bash
#BSUB -P acc_DiseaseGeneCell
#BSUB -J HER2
#BSUB -q gpu
#BSUB -R rusage[mem=30000]
#BSUB -R span[hosts=1]
#BSUB -gpu num=1
#BSUB -n 1
#BSUB -W 24:00
#BSUB -L /bin/bash
#BSUB -o out.%J.%I
#BSUB -e err.%J.%I
WKDIR="/sc/arion/work/cheny69"
SEED=1
module purge
module load anaconda3/2024.06
source ~/.bashrc
conda activate boltz0929
ml proxies/1
boltz predict $WKDIR/prot.yaml --out_dir $WKDIR/result/$SEED/ --use_msa_server --cache $WKDIR/mol/ --seed $SEED 