#!/bin/bash
#BSUB -P acc_DiseaseGeneCell
#BSUB -J HER2
#BSUB -q gpu
#BSUB -R rusage[mem=8000]
#BSUB -R span[hosts=1]
#BSUB -gpu num=1
#BSUB -n 16
#BSUB -W 24:00
#BSUB -L /bin/bash
#BSUB -o out.%J.%I
#BSUB -e err.%J.%I
module purge
module load anaconda3/2024.06
# conda create -n boltz0728 python=3.10
conda activate boltz0728
git clone https://github.com/jwohlwend/boltz.git
cd boltz; pip install -e .[cuda]
WD="/hpc/users/cheny69/"
python 